### ISSUE TITLE
Feature request: Scaling workers based on metrics

### ISSUE THREAD

**Issue by mliezun** [DefangLabs/defang#1211]
# Description

Hi Defang team!

We're heavy users of AWS and considering an EKS -> ECS migration.

We think defang could be really helpful for that.

What's stopping us is the lack of scaling workers using metrics that are not based on resource usage (ram, cpu).

## Our current stack

- Django + Celery + Redis

We're scaling our celery workers based on the number of tasks in a Redis List. We use KEDA (Kubernetes Event-driven Autoscaling) for that: https://keda.sh/docs/2.17/scalers/redis-sentinel-lists/

This is how a typical config for scaling looks like:

```yml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-worker-scaling
spec:
  scaleTargetRef:
    kind: Deployment
    name: celery-worker
  pollingInterval: 30
  cooldownPeriod: 200
  maxReplicaCount: 100
  minReplicaCount: 1
  triggers:
    - type: redis
      metadata:
        addressFromEnv: REDIS_HOST
        listName: celery-queue-name
        databaseIndex: "0"
        enableTLS: "true"
        listLength: "50"
```

The most important bit of information there is `listLength: "50"`. Which means that if we have 500 messages in the queue, we would need 500/50 = 10 workers.

## Feature request

Defang should implement some sort of Event-driven Autoscaling out of the box.

It could look like this:

```yml
celery-worker:
  image: celery-worker-image:latest
  x-defang-eda:
    pollingInterval: 30
    cooldownPeriod: 200
    maxReplicaCount: 100
    minReplicaCount: 1
    triggers:
    - type: redis
      metadata:
        addressFromEnv: REDIS_HOST
        listName: celery-queue-name
        databaseIndex: "0"
        enableTLS: "true"
        listLength: "50"
```

In AWS this requires that a metric is published to Cloudwatch and that the proper Cloudwatch alarms are set up. Then ECS autoscaling needs to be linked withe the proper alarms in order to scale up and down.

A suggestion on how to implement it is that when `x-defang-eda` is detected in a compose file an additional sidecar ECS task is created, that polls the redis list and publishes the metric to Cloudwatch.

## Closing remarks

I know this is a lot to ask. I appreciate the work that you're doing and wanted to share my perspective on it.

Thanks!
