### ISSUE TITLE
Running multiple versions at once

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#122]
I just ran into an interesting new issue (or maybe it's expected?). I deployed my app, but it seems like it takes over 6-7 minutes before the new version replaces the old version. I would usually expect a bit of overlap as the first healthchecks pass, but not this long. To be fair, the healthcheck interval is quite high, so maybe it's just that it waits for somewhere between 5-10 healthchecks to pass before removing the old containers?

```
healthcheck:
      test: ["CMD", "curl", "http://localhost:3000"]
      interval: 1m
      timeout: 10s
      retries: 10
```

![CleanShot 2024-02-26 at 19 48 26@2x](https://github.com/defang-io/defang/assets/910895/829bee07-089a-44f0-862d-ed0cbf87cc1d)
