### ISSUE TITLE
Support services with public+private hostnames

### ISSUE THREAD

**Issue by lionello** [DefangLabs/defang#1282]
First attempt was to add the listening port twice: once with `ingress` and once with `host`:
```
services:
  app:
    domainname: blah.example.com
    image: blah
    ports:
      - target: 8080
        mode: ingress
      - target: 8080
        mode: host
```
but `compose-go` silently dropped the `host` one (last one?) and the service ended up with only a public FQDN (no sidecar).

We cannot express in Compose which ports are on which networks, so perhaps the right way would be:
```
services:
  app:
    domainname: blah.example.com
    image: blah
    ports:
      - target: 8080
        mode: ingress
     networks:
        default:
        private:
```
and we should make sure that the service is discoverable on both networks. Technically this means it would get a "private" load balancer.
