### ISSUE TITLE
DNS replacement for ingress ports

### ISSUE THREAD

**Issue by lionello** [DefangLabs/defang#396]
Not just for host ports:

```
services:
  app:
     build: .
     ports:
       - target: 80
         mode: ingress
     environment:
       - FQDN=https://app # https://app-lionello.prod1.defang.dev
```

```
services:
  app:
     build: .
     ports:
       - target: 80
         mode: ingress
     domainname: example.com
     environment:
       - FQDN=https://app # https://example.com
```
