### ISSUE TITLE
Should be able to use redis as a hostname

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#547]
This fails:

```
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 3000
        published: 3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  processor:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROCESSOR=true

  redis:
    image: redis:alpine
    x-defang-redis: true
    ports:
      - 6379:6379
```

I looked back through the [BullMQ Sample](https://github.com/DefangSamples/sample-bullmq-bullboard-redis-template/blob/main/compose.yaml) and realized I probably need to change `redis` to `redisx` to make it work, but this is something I'm certain other people will run into that needs to be fixed.
