### ISSUE TITLE
Defang generate with Redis should automatically add x-defang 

### ISSUE THREAD

**Issue by raphaeltm** [DefangLabs/defang#548]
I generated a project with `defang generate` which ended up looking like this:

```
services:
  service1:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
```

Good starting point, but we should make sure that generated code includes `x-defang-redis: true` if it includes Redis at all.
