### ISSUE TITLE
Cannot Deploy basic Next.js App via Defang Compose Due to 10MB Limit

### ISSUE THREAD

**Issue by ve-varun-sharma** [DefangLabs/defang#703]
# Description

I'm attempting to deploy a simple Next.js app using Defang Compose, but I'm encountering a build context size limit of 10MB. Despite using a .dockerignore file to exclude build items and heavy files, I'm still receiving the following error:

`Error: build context is too large; this beta version is limited to 10MiB, use --debug or create .dockerignore to exclude caches and build artifacts
`

I will caveat that I do have a bunch of local images in the public directory which ends up taking exceeding the memory limit that defang has imposed on context sizes. So to explicit call out this is intended behaviour of the CLI but overall more restrictive than I had estimated. _**This is a long winded way to say that this Github issue is also a feature request issue to expand the context sizes!**_

I know that in the message that it's in "beta" mode but I thought it was worth to still mention here for visibility that deployments of relatively very light apps are quite restricted and hopefully we can have these context sizes expanded soon!

As a sanity check too - hopefully I didn't miss anything and my assumptions are not incorrect about what I think the problem is. I see that there are some warnings which are quiet easily fixable but the main show shopper is the context size.

# Screenshots
![image](https://github.com/user-attachments/assets/94470916-99fa-4df6-9dfd-a2c089d75f9a)

# Code Snippets

### .dockerignore file:

```
# ignore .git and .cache folders
.git
.cache
#Ignore the logs directory
logs/

#Ignoring the password file
passwords.txt

#Ignoring all the markdown and class files
*.md
**/*.class

.git/
tests/
# Ignore Node Modules
**/modules
node_modules/

# Ignore docker compose for dev
npm-debug
docker-compose*.yml
docker-compose.yml

# Next items
.next
```

### docker-compose.yaml file:

```
version: "3.7"

services:
  ve-portfolio-site:
    container_name: ve-portfolio-site
    restart: unless-stopped
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - 3000:3000
      - mode: ingress
        target: 3000
    expose:
      - "3000"
    stdin_open: true
    deploy:
      resources:
        reservations:
          memory: 1GB

```

### Dockerfile:

```
FROM node:18-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package*.json ./
RUN pnpm i

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1

RUN pnpm run build

FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

USER nextjs

EXPOSE $PORT
CMD ["pnpm", "start"]


```
